// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34003
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace nuserv.UiTests.Repository
{
    using TechTalk.SpecFlow;
    using Autofac;
    using Autofac.Configuration;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Overview")]
    public partial class OverviewFeature
    {
        
        private OpenQA.Selenium.IWebDriver driver;
        
        private IContainer container;
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Overview.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            var builder = new ContainerBuilder();
            builder.RegisterModule(new ConfigurationSettingsReader());
            this.container = builder.Build();
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Overview", "In order to manage the nuget repositories I\'ve setup \nAs a user\nI want to see an " +
                    "overview of my repositories", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            if(this.driver != null)
                ScenarioContext.Current.Add("Driver", this.driver);
            if(this.container != null)
                ScenarioContext.Current.Add("Container", this.container);
        }
        
        public virtual void ScenarioCleanup()
        {
            try { System.Threading.Thread.Sleep(50); this.driver.Quit(); } catch (System.Exception) {}
            this.driver = null;
            ScenarioContext.Current.Remove("Driver");
            ScenarioContext.Current.Remove("Container");
            testRunner.CollectScenarioErrors();
        }
        
        private void InitializeSelenium(string browser)
        {
            this.driver = this.container.ResolveNamed<OpenQA.Selenium.IWebDriver>(browser);
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Navigate to repository")]
        [NUnit.Framework.TestCaseAttribute("IE", Category="IE", TestName="NavigateToRepository on IE")]
        [NUnit.Framework.TestCaseAttribute("Firefox", Category="Firefox", TestName="NavigateToRepository on Firefox")]
        [NUnit.Framework.TestCaseAttribute("Chrome", Category="Chrome", TestName="NavigateToRepository on Chrome")]
        public virtual void NavigateToRepository(string browser)
        {
            InitializeSelenium(browser);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigate to repository", new string[] {
                        "Browser:IE",
                        "Browser:Firefox",
                        "Browser:Chrome"});
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.Given("I navigated to /repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
 testRunner.Then("the browser title should be \"nuserv repositories\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
 testRunner.And("the title should be \"repositories\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("the lead should be \"manage repositories\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Look at list of repositories")]
        [NUnit.Framework.TestCaseAttribute("IE", Category="IE", TestName="LookAtListOfRepositories on IE")]
        [NUnit.Framework.TestCaseAttribute("Firefox", Category="Firefox", TestName="LookAtListOfRepositories on Firefox")]
        [NUnit.Framework.TestCaseAttribute("Chrome", Category="Chrome", TestName="LookAtListOfRepositories on Chrome")]
        public virtual void LookAtListOfRepositories(string browser)
        {
            InitializeSelenium(browser);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Look at list of repositories", new string[] {
                        "Browser:IE",
                        "Browser:Firefox",
                        "Browser:Chrome"});
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
 testRunner.Given("I navigated to /repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
 testRunner.Then("I should see 1 existing repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
 testRunner.And("I should see a form to create a new repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Look at list of repositories details")]
        [NUnit.Framework.TestCaseAttribute("IE", Category="IE", TestName="LookAtListOfRepositoriesDetails on IE")]
        [NUnit.Framework.TestCaseAttribute("Firefox", Category="Firefox", TestName="LookAtListOfRepositoriesDetails on Firefox")]
        [NUnit.Framework.TestCaseAttribute("Chrome", Category="Chrome", TestName="LookAtListOfRepositoriesDetails on Chrome")]
        public virtual void LookAtListOfRepositoriesDetails(string browser)
        {
            InitializeSelenium(browser);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Look at list of repositories details", new string[] {
                        "Browser:IE",
                        "Browser:Firefox",
                        "Browser:Chrome"});
#line 26
this.ScenarioSetup(scenarioInfo);
#line 27
 testRunner.Given("I navigated to /repository", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "ApiUrl",
                        "FeedUrl",
                        "Description"});
            table1.AddRow(new string[] {
                        "external/ProjectX",
                        "repository/external-projectx",
                        "repository/external-projectx/api/v2",
                        "Curated nuget repository for project projectX"});
#line 28
 testRunner.Then("I should see the following repositories:", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
